SELECT
  NIVEL.IDBAIRRO,
  RUA.DESCRRUA,
  BLOCO.DESCRBLOCO,
  NIVEL.DESCRNIVEL
FROM DBA.PRODUTO_ENDERECO_NIVEL NIVEL
LEFT JOIN DBA.PRODUTO_ENDERECO_BLOCO BLOCO
  ON NIVEL.IDEMPRESA = BLOCO.IDEMPRESA
  AND NIVEL.IDBAIRRO = BLOCO.IDBAIRRO
  AND NIVEL.IDRUA    = BLOCO.IDRUA
  AND NIVEL.IDBLOCO  = BLOCO.IDBLOCO
LEFT JOIN DBA.PRODUTO_ENDERECO_RUA RUA
  ON NIVEL.IDEMPRESA = RUA.IDEMPRESA
  AND NIVEL.IDBAIRRO = RUA.IDBAIRRO
  AND NIVEL.IDRUA    = RUA.IDRUA
FOR READ ONLY