SELECT
    CP.IDEMPRESA,
    CP.IDCLIFOR,
    CP.IDPRODUTO,
    COALESCE(RTRIM(PF.CODIGOINTERNOFORN), '') AS CODIGOINTERNOFORN,
    CP.NUMNOTA,
    CP.QTDPRODUTO,
    PG.DESCRRESPRODUTO,
    CP.IDAUTORIZACAO
FROM CONFERE_PEDIDO CP
INNER JOIN CONFERE_AUTORIZA CA
    ON CA.IDAUTORIZACAO = CP.IDAUTORIZACAO
   AND CA.IDCLIFOR = CP.IDCLIFOR
   AND CA.IDEMPRESA = CP.IDEMPRESA
   AND CA.NUMNOTA = CP.NUMNOTA
   AND CA.SERIENOTA = CP.SERIENOTA
INNER JOIN PRODUTO_GRADE PG
    ON PG.IDPRODUTO = CP.IDPRODUTO
   AND PG.IDSUBPRODUTO = CP.IDSUBPRODUTO
LEFT JOIN PRODUTO_FORNECEDOR PF
    ON PF.IDCLIFOR = CP.IDCLIFOR
   AND PF.IDPRODUTO = CP.IDPRODUTO
   AND PF.IDSUBPRODUTO = CP.IDSUBPRODUTO
WHERE CA.DTMOVIMENTO BETWEEN DATE('2026-01-01') AND CURRENT DATE
FOR READ ONLY;