SELECT
    CP.IDEMPRESA,
    CP.IDCLIFOR,
    CP.IDPRODUTO,
    COALESCE(RTRIM(PF.CODIGOINTERNOFORN), '') AS CODIGOINTERNOFORN,
    CP.NUMNOTA,
    CP.QTDPRODUTO,
    PG.DESCRRESPRODUTO,
    CP.IDAUTORIZACAO,
    CA.SERIENOTA
FROM DBA.CONFERE_PEDIDO CP
INNER JOIN DBA.CONFERE_AUTORIZA CA
    ON CA.IDAUTORIZACAO = CP.IDAUTORIZACAO
   AND CA.IDCLIFOR = CP.IDCLIFOR
   AND CA.IDEMPRESA = CP.IDEMPRESA
   AND CA.NUMNOTA = CP.NUMNOTA
   AND CA.SERIENOTA = CP.SERIENOTA
INNER JOIN DBA.PRODUTO_GRADE PG
    ON PG.IDPRODUTO = CP.IDPRODUTO
   AND PG.IDSUBPRODUTO = CP.IDSUBPRODUTO
LEFT JOIN DBA.PRODUTO_FORNECEDOR PF
    ON PF.IDCLIFOR = CP.IDCLIFOR
   AND PF.IDPRODUTO = CP.IDPRODUTO
   AND PF.IDSUBPRODUTO = CP.IDSUBPRODUTO
WHERE CP.IDEMPRESA IN (1, 3)
  AND CA.DTMOVIMENTO BETWEEN CURRENT DATE - 60 DAYS AND CURRENT DATE
FOR READ ONLY
